"""initial_schema

Revision ID: 62eca980f855
Revises: 
Create Date: 2026-07-25 16:25:34.079492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62eca980f855'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('props', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_name'), 'events', ['event_name'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'rate_date', name='uq_fxrate_ccy_date')
    )
    op.create_index(op.f('ix_fx_rates_currency'), 'fx_rates', ['currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_rate_date'), 'fx_rates', ['rate_date'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('yf_symbol', sa.String(length=40), nullable=True),
    sa.Column('yf_unlisted', sa.Boolean(), nullable=True),
    sa.Column('asset_class', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('next_earnings_date', sa.Date(), nullable=True),
    sa.Column('next_earnings_sourced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'currency', name='uq_security_symbol_ccy')
    )
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_tenant_id'), 'portfolios', ['tenant_id'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'bar_date', name='uq_pricebar_security_date')
    )
    op.create_index(op.f('ix_price_bars_bar_date'), 'price_bars', ['bar_date'], unique=False)
    op.create_index(op.f('ix_price_bars_security_id'), 'price_bars', ['security_id'], unique=False)
    op.create_table('security_classifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'symbol', name='uq_security_classification_symbol')
    )
    op.create_index(op.f('ix_security_classifications_tenant_id'), 'security_classifications', ['tenant_id'], unique=False)
    op.create_table('security_labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'symbol', name='uq_security_label_symbol')
    )
    op.create_index(op.f('ix_security_labels_tenant_id'), 'security_labels', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('identity_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tos_accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_identity_user_id'), 'users', ['identity_user_id'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('account_type', sa.String(length=60), nullable=True),
    sa.Column('tax_treatment', sa.String(length=20), nullable=True),
    sa.Column('taxable_override', sa.Boolean(), nullable=True),
    sa.Column('cash_balance_usd', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'broker', 'external_id', name='uq_account_source')
    )
    op.create_index(op.f('ix_accounts_portfolio_id'), 'accounts', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('crypto_value_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'portfolio_id', 'snap_date', name='uq_crypto_value_snapshot_day')
    )
    op.create_index(op.f('ix_crypto_value_snapshots_portfolio_id'), 'crypto_value_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_crypto_value_snapshots_snap_date'), 'crypto_value_snapshots', ['snap_date'], unique=False)
    op.create_index(op.f('ix_crypto_value_snapshots_tenant_id'), 'crypto_value_snapshots', ['tenant_id'], unique=False)
    op.create_table('intraday_leg_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('overnight_pct', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('intraday_pct', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('day_pct', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('overnight_gain', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('intraday_gain', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('day_gain', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('prev_mv', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('n_priced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'portfolio_id', 'snap_date', name='uq_intraday_leg_day')
    )
    op.create_index(op.f('ix_intraday_leg_snapshots_portfolio_id'), 'intraday_leg_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_intraday_leg_snapshots_snap_date'), 'intraday_leg_snapshots', ['snap_date'], unique=False)
    op.create_index(op.f('ix_intraday_leg_snapshots_tenant_id'), 'intraday_leg_snapshots', ['tenant_id'], unique=False)
    op.create_table('investor_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('objective', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('snaptrade_excluded_connections', sa.String(length=2000), nullable=True),
    sa.Column('excluded_account_keys', sa.String(length=4000), nullable=True),
    sa.Column('selected_account_ids', sa.String(length=4000), nullable=True),
    sa.Column('intraday_enabled', sa.Boolean(), nullable=True),
    sa.Column('holdings_grouping', sa.String(length=20), nullable=True),
    sa.Column('holdings_visible_bands', sa.String(length=120), nullable=True),
    sa.Column('holdings_combine_by_account', sa.Boolean(), nullable=True),
    sa.Column('holdings_hidden_types', sa.String(length=120), nullable=True),
    sa.Column('holdings_valuation', sa.String(length=12), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'portfolio_id', name='uq_investorpref_portfolio')
    )
    op.create_index(op.f('ix_investor_preferences_portfolio_id'), 'investor_preferences', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_investor_preferences_tenant_id'), 'investor_preferences', ['tenant_id'], unique=False)
    op.create_table('nav_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('external_flow', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('spy_close', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('provisional', sa.Boolean(), nullable=True),
    sa.Column('composition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'portfolio_id', 'snap_date', name='uq_navsnapshot_day')
    )
    op.create_index(op.f('ix_nav_snapshots_portfolio_id'), 'nav_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_nav_snapshots_snap_date'), 'nav_snapshots', ['snap_date'], unique=False)
    op.create_index(op.f('ix_nav_snapshots_tenant_id'), 'nav_snapshots', ['tenant_id'], unique=False)
    op.create_table('wallet_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'portfolio_id', 'chain', 'address', name='uq_wallet_address')
    )
    op.create_index(op.f('ix_wallet_addresses_portfolio_id'), 'wallet_addresses', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_wallet_addresses_tenant_id'), 'wallet_addresses', ['tenant_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'portfolio_id', 'symbol', name='uq_watchlist_symbol')
    )
    op.create_index(op.f('ix_watchlist_items_portfolio_id'), 'watchlist_items', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_tenant_id'), 'watchlist_items', ['tenant_id'], unique=False)
    op.create_table('account_nav_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('external_flow', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('spy_close', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('provisional', sa.Boolean(), nullable=True),
    sa.Column('composition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_id', 'snap_date', name='uq_account_navsnapshot_day')
    )
    op.create_index(op.f('ix_account_nav_snapshots_account_id'), 'account_nav_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_nav_snapshots_portfolio_id'), 'account_nav_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_account_nav_snapshots_snap_date'), 'account_nav_snapshots', ['snap_date'], unique=False)
    op.create_index(op.f('ix_account_nav_snapshots_tenant_id'), 'account_nav_snapshots', ['tenant_id'], unique=False)
    op.create_table('open_lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_lots_account_id'), 'open_lots', ['account_id'], unique=False)
    op.create_index(op.f('ix_open_lots_open_date'), 'open_lots', ['open_date'], unique=False)
    op.create_index(op.f('ix_open_lots_tenant_id'), 'open_lots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_open_lots_ticker'), 'open_lots', ['ticker'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('market_value_local', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'security_id', name='uq_position_account_security')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_positions_as_of'), 'positions', ['as_of'], unique=False)
    op.create_index(op.f('ix_positions_security_id'), 'positions', ['security_id'], unique=False)
    op.create_index(op.f('ix_positions_tenant_id'), 'positions', ['tenant_id'], unique=False)
    op.create_table('realized_lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('proceeds', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('lot_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lot_key', name='uq_realized_lot')
    )
    op.create_index(op.f('ix_realized_lots_account_id'), 'realized_lots', ['account_id'], unique=False)
    op.create_index(op.f('ix_realized_lots_close_date'), 'realized_lots', ['close_date'], unique=False)
    op.create_index(op.f('ix_realized_lots_lot_key'), 'realized_lots', ['lot_key'], unique=False)
    op.create_index(op.f('ix_realized_lots_tenant_id'), 'realized_lots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_realized_lots_ticker'), 'realized_lots', ['ticker'], unique=False)
    op.create_table('reconciliation_breaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=True),
    sa.Column('break_type', sa.String(length=30), nullable=False),
    sa.Column('break_key', sa.String(length=140), nullable=False),
    sa.Column('break_date', sa.Date(), nullable=False),
    sa.Column('metron_value', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('broker_value', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('alerted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('break_key', name='uq_reconciliation_break_key')
    )
    op.create_index(op.f('ix_reconciliation_breaks_account_id'), 'reconciliation_breaks', ['account_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_breaks_break_date'), 'reconciliation_breaks', ['break_date'], unique=False)
    op.create_index(op.f('ix_reconciliation_breaks_break_key'), 'reconciliation_breaks', ['break_key'], unique=False)
    op.create_index(op.f('ix_reconciliation_breaks_security_id'), 'reconciliation_breaks', ['security_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_breaks_tenant_id'), 'reconciliation_breaks', ['tenant_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=True),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_id', 'source_key', name='uq_txn_source_key')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_security_id'), 'transactions', ['security_id'], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transactions_trade_date'), 'transactions', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_trade_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_security_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reconciliation_breaks_tenant_id'), table_name='reconciliation_breaks')
    op.drop_index(op.f('ix_reconciliation_breaks_security_id'), table_name='reconciliation_breaks')
    op.drop_index(op.f('ix_reconciliation_breaks_break_key'), table_name='reconciliation_breaks')
    op.drop_index(op.f('ix_reconciliation_breaks_break_date'), table_name='reconciliation_breaks')
    op.drop_index(op.f('ix_reconciliation_breaks_account_id'), table_name='reconciliation_breaks')
    op.drop_table('reconciliation_breaks')
    op.drop_index(op.f('ix_realized_lots_ticker'), table_name='realized_lots')
    op.drop_index(op.f('ix_realized_lots_tenant_id'), table_name='realized_lots')
    op.drop_index(op.f('ix_realized_lots_lot_key'), table_name='realized_lots')
    op.drop_index(op.f('ix_realized_lots_close_date'), table_name='realized_lots')
    op.drop_index(op.f('ix_realized_lots_account_id'), table_name='realized_lots')
    op.drop_table('realized_lots')
    op.drop_index(op.f('ix_positions_tenant_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_security_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_as_of'), table_name='positions')
    op.drop_index(op.f('ix_positions_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_open_lots_ticker'), table_name='open_lots')
    op.drop_index(op.f('ix_open_lots_tenant_id'), table_name='open_lots')
    op.drop_index(op.f('ix_open_lots_open_date'), table_name='open_lots')
    op.drop_index(op.f('ix_open_lots_account_id'), table_name='open_lots')
    op.drop_table('open_lots')
    op.drop_index(op.f('ix_account_nav_snapshots_tenant_id'), table_name='account_nav_snapshots')
    op.drop_index(op.f('ix_account_nav_snapshots_snap_date'), table_name='account_nav_snapshots')
    op.drop_index(op.f('ix_account_nav_snapshots_portfolio_id'), table_name='account_nav_snapshots')
    op.drop_index(op.f('ix_account_nav_snapshots_account_id'), table_name='account_nav_snapshots')
    op.drop_table('account_nav_snapshots')
    op.drop_index(op.f('ix_watchlist_items_tenant_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_portfolio_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_wallet_addresses_tenant_id'), table_name='wallet_addresses')
    op.drop_index(op.f('ix_wallet_addresses_portfolio_id'), table_name='wallet_addresses')
    op.drop_table('wallet_addresses')
    op.drop_index(op.f('ix_nav_snapshots_tenant_id'), table_name='nav_snapshots')
    op.drop_index(op.f('ix_nav_snapshots_snap_date'), table_name='nav_snapshots')
    op.drop_index(op.f('ix_nav_snapshots_portfolio_id'), table_name='nav_snapshots')
    op.drop_table('nav_snapshots')
    op.drop_index(op.f('ix_investor_preferences_tenant_id'), table_name='investor_preferences')
    op.drop_index(op.f('ix_investor_preferences_portfolio_id'), table_name='investor_preferences')
    op.drop_table('investor_preferences')
    op.drop_index(op.f('ix_intraday_leg_snapshots_tenant_id'), table_name='intraday_leg_snapshots')
    op.drop_index(op.f('ix_intraday_leg_snapshots_snap_date'), table_name='intraday_leg_snapshots')
    op.drop_index(op.f('ix_intraday_leg_snapshots_portfolio_id'), table_name='intraday_leg_snapshots')
    op.drop_table('intraday_leg_snapshots')
    op.drop_index(op.f('ix_crypto_value_snapshots_tenant_id'), table_name='crypto_value_snapshots')
    op.drop_index(op.f('ix_crypto_value_snapshots_snap_date'), table_name='crypto_value_snapshots')
    op.drop_index(op.f('ix_crypto_value_snapshots_portfolio_id'), table_name='crypto_value_snapshots')
    op.drop_table('crypto_value_snapshots')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_portfolio_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_identity_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_labels_tenant_id'), table_name='security_labels')
    op.drop_table('security_labels')
    op.drop_index(op.f('ix_security_classifications_tenant_id'), table_name='security_classifications')
    op.drop_table('security_classifications')
    op.drop_index(op.f('ix_price_bars_security_id'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_bar_date'), table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_portfolios_tenant_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_fx_rates_rate_date'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_currency'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_name'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
