"""add shadow_recompute_breaks

The layer-2 sibling of ``reconciliation_breaks`` (see ``api.db.models`` for why it is a
separate table rather than a row shape in layer 1) shipped as a model with **no
migration**. On SQLite that was invisible — ``api.db.session.create_all`` builds the
whole schema from the models — but ``create_all`` returns immediately on Postgres by
design ("Alembic owns schema evolution; never auto-DDL here"), so the table simply does
not exist on Neon. Confirmed 2026-08-03 by diffing ``Base.metadata`` against the live
inspector: exactly one missing table, no missing columns.

Hand-written rather than autogenerated, because autogenerate against the live DB would
also have to be run from a machine that can reach Neon and would pick up unrelated
drift; the column set here is transcribed from ``models.ShadowRecomputeBreak`` and
mirrors the ``reconciliation_breaks`` block of the initial migration exactly.

Revision ID: a1f2c3d4e5b6
Revises: 62eca980f855
Create Date: 2026-08-03

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1f2c3d4e5b6'
down_revision: Union[str, Sequence[str], None] = '62eca980f855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'shadow_recompute_breaks',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('portfolio_id', sa.Uuid(), nullable=False),
        sa.Column('break_type', sa.String(length=30), nullable=False),
        sa.Column('break_key', sa.String(length=140), nullable=False),
        sa.Column('break_date', sa.Date(), nullable=False),
        sa.Column('as_of_date', sa.Date(), nullable=False),
        sa.Column('production_value', sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column('shadow_value', sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column('tolerance', sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column('alerted_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('break_key', name='uq_shadow_recompute_break_key'),
    )
    op.create_index(
        op.f('ix_shadow_recompute_breaks_as_of_date'), 'shadow_recompute_breaks', ['as_of_date'], unique=False
    )
    op.create_index(
        op.f('ix_shadow_recompute_breaks_break_date'), 'shadow_recompute_breaks', ['break_date'], unique=False
    )
    op.create_index(
        op.f('ix_shadow_recompute_breaks_break_key'), 'shadow_recompute_breaks', ['break_key'], unique=False
    )
    op.create_index(
        op.f('ix_shadow_recompute_breaks_portfolio_id'), 'shadow_recompute_breaks', ['portfolio_id'], unique=False
    )
    op.create_index(
        op.f('ix_shadow_recompute_breaks_tenant_id'), 'shadow_recompute_breaks', ['tenant_id'], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_shadow_recompute_breaks_tenant_id'), table_name='shadow_recompute_breaks')
    op.drop_index(op.f('ix_shadow_recompute_breaks_portfolio_id'), table_name='shadow_recompute_breaks')
    op.drop_index(op.f('ix_shadow_recompute_breaks_break_key'), table_name='shadow_recompute_breaks')
    op.drop_index(op.f('ix_shadow_recompute_breaks_break_date'), table_name='shadow_recompute_breaks')
    op.drop_index(op.f('ix_shadow_recompute_breaks_as_of_date'), table_name='shadow_recompute_breaks')
    op.drop_table('shadow_recompute_breaks')
