"""add reconciliation_fetch_status

Layer-1 reconciliation persisted only its *breaks*, never the fact that a fetch had
happened — so "when did this broker last reconcile successfully?" was unanswerable, and
the nightly CLI, unable to tell one bad night from a dead detector, exited non-zero on
both. This table is the missing record (metron-ops#274).

Hand-written rather than autogenerated, matching the a1f2c3d4e5b6 precedent: autogenerate
would have to run against Neon from a machine that can reach it and would sweep up
unrelated drift. Columns transcribed from ``models.ReconciliationFetchStatus``.

Revision ID: b7d3e91a4c2f
Revises: a1f2c3d4e5b6
Create Date: 2026-08-21

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7d3e91a4c2f'
down_revision: Union[str, Sequence[str], None] = 'a1f2c3d4e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'reconciliation_fetch_status',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('portfolio_id', sa.Uuid(), nullable=False),
        sa.Column('broker', sa.String(length=30), nullable=False),
        sa.Column('last_success_at', sa.DateTime(), nullable=True),
        sa.Column('last_failure_at', sa.DateTime(), nullable=True),
        sa.Column('last_error', sa.String(length=500), nullable=True),
        sa.Column('consecutive_failures', sa.Integer(), nullable=False),
        sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('portfolio_id', 'broker', name='uq_reconciliation_fetch_portfolio_broker'),
    )
    op.create_index(
        op.f('ix_reconciliation_fetch_status_portfolio_id'),
        'reconciliation_fetch_status',
        ['portfolio_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_reconciliation_fetch_status_tenant_id'), 'reconciliation_fetch_status', ['tenant_id'], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_reconciliation_fetch_status_tenant_id'), table_name='reconciliation_fetch_status')
    op.drop_index(op.f('ix_reconciliation_fetch_status_portfolio_id'), table_name='reconciliation_fetch_status')
    op.drop_table('reconciliation_fetch_status')
