"""add plan_targets

User-authored per-security plan targets (metron-ops-I311): the "New cash to my targets"
and "What-if purchase" comparator to deploy cash — arithmetic against a table the user
typed in, never a Metron-chosen allocation. Existing ``target_allocation`` lives in the
private ``metron_ext`` advisor profile and is a coarse us_equity/international split; this
is a new, public, per-security table.

Hand-written rather than autogenerated, matching the b7d3e91a4c2f / a1f2c3d4e5b6 precedent.
Columns transcribed from ``models.PlanTarget``.

Revision ID: c9e4f27a1b83
Revises: b7d3e91a4c2f
Create Date: 2026-09-15

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c9e4f27a1b83'
down_revision: Union[str, Sequence[str], None] = 'b7d3e91a4c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'plan_targets',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('portfolio_id', sa.Uuid(), nullable=False),
        sa.Column('targets', sa.JSON(), nullable=False),
        sa.Column('max_single_position', sa.Float(), nullable=True),
        sa.Column('min_line_usd', sa.Float(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'portfolio_id', name='uq_plantarget_portfolio'),
    )
    op.create_index(op.f('ix_plan_targets_portfolio_id'), 'plan_targets', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_plan_targets_tenant_id'), 'plan_targets', ['tenant_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_plan_targets_tenant_id'), table_name='plan_targets')
    op.drop_index(op.f('ix_plan_targets_portfolio_id'), table_name='plan_targets')
    op.drop_table('plan_targets')
